### ISSUE TITLE
Waveshare 7.8" IT8951 communication failed

### ISSUE THREAD

**Issue by grooverkm** [robweber/omni-epd#93]
Hoping this is a simple problem someone can help me resolve. Trying to set up a raspberry pi zero with 32-bit bookworm and a 7.8" Waveshare IT8951 display, in order to run SlowMovie.

Hardware passes the Waveshare self-tests and displays correctly (actually displays as 10.3inch e-Paper, which makes me believe it is supported under the same IT8951 profile in omni-epd), but when I try and run either slowmovie or omni-epd-test I get the same traceback:-

Traceback (most recent call last):
  File "/home/pi/SlowMovie/slowmovie.py", line 264, in <module>
    epd = displayfactory.load_display_driver(args.epd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/SlowMovie/.SlowMovie/lib/python3.11/site-packages/omni_epd/displayfactory.py", line 113, in load_display_driver
    result = classObj(deviceType[1], config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/SlowMovie/.SlowMovie/lib/python3.11/site-packages/omni_epd/displays/waveshare_display.py", line 462, in __init__
    self._device = deviceObj.AutoEPDDisplay(vcom=self._getfloat_device_option('vcom', -1.40),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/SlowMovie/.SlowMovie/lib/python3.11/site-packages/IT8951/display.py", line 215, in __init__
    epd = EPD(vcom=vcom, bus=bus, device=device, data_hz=spi_hz)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/SlowMovie/.SlowMovie/lib/python3.11/site-packages/IT8951/interface.py", line 35, in __init__
    self.update_system_info()
  File "/home/pi/SlowMovie/.SlowMovie/lib/python3.11/site-packages/IT8951/interface.py", line 105, in update_system_info
    raise RuntimeError("communication with device failed")
RuntimeError: communication with device failed

Any ideas or help with what I may be doing wrong?

**Comment by robweber** [comment]
Do you have a link to the Waveshare self-tests? I'm not familiar with them. Waveshare doesn't supply Python drivers themselves for the IT8951. One thought is did you [enable SPI ](https://www.raspberrypi-spy.co.uk/2014/08/enabling-the-spi-interface-on-the-raspberry-pi/)on your Rpi?

**Comment by robweber** [comment]
Just circling back to this I'm curious if you tried to reboot your Rpi since running the Waveshare demo code? A few places I've seen say that the Waveshare demo code doesn't close the SPI communications properly and after that things fail. Reboots of the OS seem to fix it.

**Comment by robweber** [comment]
Any luck with this? The IT8951 repo page (link above) might have more help if you're still plugging away at it. That error looks like it can't enable SPI correctly - maybe the spidev module isn't loaded properly? At this point all these errors are pretty low level OS stuff. As much as it sucks a complete reimaging of the SD card with a fresh OS might be in order.

**Comment by grooverkm** [comment]
Hi, thanks for following up. I am still plugging away. I reimaged with a fresh OS and tried another project, PaperPi [https://github.com/txoof/PaperPi](url), as a sanity check and to see if it is hardware related. That project works fine so I am reasonably sure it is on the software side - maybe something to do with the venv that SlowMovie creates. Appreciate all the help and any ideas.

**Comment by robweber** [comment]
That is weird that the other project works. PaperPi uses the [exact same](https://github.com/txoof/PaperPi/blob/main/requirements.txt#L5) underlying driver for the IT8951 displays. Given that your original error was due to code from that project I wouldn't jump to any issue with SlowMovie specifically.
